version: '3.8'

services:
  business-1:
    &worker
    container_name: business-1
    image: ha-business
    build:
      context: .
    environment:
      - INVENTORY_URL=http://10.0.0.6:8200   #記得改成ip
      - MYSQL_HOST=10.0.0.7   #記得改成ip
      - MYSQL_PORT=8300
      # - REDIS_HOST=cache
    ports:
      - 10.0.0.5:3000:3000
    restart: always

  business-2:
    <<: *worker
    container_name: business-2
    image: ha-business
    environment:
      - INVENTORY_URL=http://10.0.0.6:8200   #記得改成ip
      - MYSQL_HOST=10.0.0.7   #記得改成ip
      - MYSQL_PORT=8300
      # - REDIS_HOST=cache
    ports:
      - 10.0.0.5:3001:3000
    restart: always

  # load-balancer:
  #   container_name: load-balancer
  #   image: nginx:alpine
  #   ports:
  #     - 8100:8100
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro

  # cache:
  #     container_name: redis
  #     image: redis:alpine
  #     restart: always
  #     ports:
  #       - 6379:6379
  #     healthcheck:
  #       test: redis-cli ping
  #       interval: 10s
  #       timeout: 5s
  #       retries: 5
  #       start_period: 3s