version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 8300:3306
    environment:
      MYSQL_ROOT_PASSWORD: cerana
      MYSQL_DATABASE: tsmc_storage
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ../init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: