apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: inventory
        tier: backend
    spec:
      containers:
        - name: inventory
          image: seco1024/ha-inventory
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
          ports:
            - containerPort: 4000